In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.1'

In [4]:
arr = np.array([25,25,67,80,89])
arr



array([25, 25, 67, 80, 89])

In [6]:
ls = [19,28,37,46,55]
arr = np.array(ls)
arr

array([19, 28, 37, 46, 55])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim


1

In [9]:
arr.size

5

In [10]:
len(arr)

5

In [11]:
arr.dtype

dtype('int64')

In [12]:
arr

array([19, 28, 37, 46, 55])

In [17]:
arr = np.array([25,25,67,80,8])
arr

array(['25', '25', '67', '80', '8', 'hii'], dtype='<U21')

In [18]:
arr.dtype

dtype('<U21')

In [19]:
arr = np.array([25,25,67,80,8])
arr

array([25, 25, 67, 80,  8])

In [20]:
arr[2]

np.int64(67)

In [29]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [22]:
arr[6-2:]

array([40, 50, 60])

In [25]:
arr[-1:-4:-1]

array([60, 50, 40])

In [30]:
arr+6


array([31, 16, 26, 36, 46, 56, 66])

In [31]:
np.mean(arr)

np.float64(33.57142857142857)

In [32]:
np.median(arr)

np.float64(30.0)

In [33]:
np.mod(arr)

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [ ]:
np.random.randint()

In [34]:
import random

In [35]:
random.randint(1,9)

2

In [36]:
random.randint(1,9)

6

In [38]:
random.randint(1,9)

9

In [39]:
random.randint(1,9)

8

In [40]:
random.randint(1,9)

5

In [15]:
arr = np.random.randint(1,450,600)
arr
#try to calculate no of item that are less than 100
#try to calculate no of even count

array([373, 161, 408, 278, 330, 317, 375, 306, 309, 418,  84,   5, 315,
       215,  84, 217, 341, 419,  48, 128, 344, 429, 352, 261, 234,   3,
       444,  18, 133, 289,  78, 135,  68, 292, 237, 261,  89, 211,  48,
       210,  49,  73,  44, 368, 407, 185, 256,  56, 293, 260,  58, 173,
       120, 300, 195, 176,  12, 122, 304,  74, 362, 214, 271, 159, 120,
       234,  48, 190, 355, 318, 140,  61,  54, 334, 277, 168, 410, 301,
       216, 202, 315, 388, 232, 130, 169, 431, 132,  85,  10,  57, 258,
         4, 398,  16, 244, 221, 328, 372,  36, 155, 110, 210, 167, 337,
       306, 332, 177, 206, 159, 361, 426,  21, 315, 379, 226, 256, 323,
        40, 448, 304,  59, 343, 343,  74, 367, 289,  57, 278, 264, 256,
         3,  75, 429, 253, 404, 143, 335,  32,  50, 316,  32, 182, 261,
       120, 435,  20, 159, 147,  36,  90, 173, 331, 125,  34, 346,  69,
       378, 385,  47, 156, 179, 275, 238, 204,  23, 378, 176, 153, 366,
       400, 213, 277, 342, 225, 240, 109, 310, 419, 115, 167, 27

In [16]:
mask = arr < 100

# Count the number of True values in the mask
count = np.sum(mask)

print("Number of items less than 100:", count)

Number of items less than 100: 128


In [17]:
mask = (arr % 2 == 0)

# Count the number of True values in the mask
count_even = np.sum(mask)

print(f'Number of even numbers: {count_even}')

Number of even numbers: 307


In [13]:
import numpy as np
# 2 D aaray
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [60]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [61]:
arr2[-1]

array([7, 8, 9])

In [64]:
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [68]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [75]:
arr2[-2:,-3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2[:,-1:]

array([[3],
       [6],
       [9]])

In [80]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
import numpy as np
np

<module 'numpy' from 'c:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>

In [12]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [10]:
#3 D array
ls = [[[1, 2, 3], [4, 5, 6],
       [7, 8, 9]],[[1, 2, 3],
      [4, 5, 6], [7, 8, 9]],
       [[1, 2, 3], [4, 5, 6],
        [7, 8, 9]],[[1, 2, 3], 
         [4, 5, 6], [7, 8, 9]]]
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [11]:
arr3 = np.array(ls)

In [96]:
arr3.ndim

3

In [17]:
arr3.shape

(4, 3, 3)

In [18]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [100]:
arr3[1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr3.size

36

In [19]:
arr3[:,0]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [107]:
arr3[0:4,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
arr3[0,1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
arr3[:,1:3,1:3]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [25]:
arr3[3,1:3,0:2]

array([[4, 5],
       [7, 8]])

In [26]:
arr3[:,-2:,-2:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [31]:
arr3[:,2, 0:]

array([[7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

In [12]:
arr3[:,2,-1::-1]

array([[9, 8, 7],
       [9, 8, 7],
       [9, 8, 7],
       [9, 8, 7]])

In [33]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr3.reshape(36,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])